name: aiq-predict

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.16'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute python workflow
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python predict.py

      - name: publish github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated graph published"
